# Generated by Django 5.1.2 on 2025-09-22 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role_type', models.CharField(choices=[('harry', '哈利波特'), ('socrates', '苏格拉底'), ('custom', '自定义')], max_length=20)),
                ('description', models.TextField()),
                ('temperature', models.FloatField(default=0.7)),
                ('top_p', models.FloatField(default=0.9)),
                ('top_k', models.IntegerField(default=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='chatrecord',
            name='character',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.character'),
        ),
    ]
