# Generated by Django 5.1.2 on 2025-09-24 05:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_character_chatrecord_character'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatrecord',
            name='character_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatrecord',
            name='character_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatrecord',
            name='temperature',
            field=models.FloatField(default=0.7),
        ),
        migrations.AddField(
            model_name='chatrecord',
            name='top_k',
            field=models.IntegerField(default=40),
        ),
        migrations.AddField(
            model_name='chatrecord',
            name='top_p',
            field=models.FloatField(default=0.9),
        ),
        migrations.AlterField(
            model_name='character',
            name='role_type',
            field=models.CharField(choices=[('harry', '哈利波特'), ('socrates', '苏格拉底'), ('custom', '自定义')], default='custom', max_length=20),
        ),
        migrations.AlterField(
            model_name='chatrecord',
            name='character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.character'),
        ),
        migrations.AlterField(
            model_name='chatrecord',
            name='content',
            field=models.JSONField(default=dict),
        ),
    ]
