# Generated by Django 5.1.2 on 2025-09-24 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatrecord_character_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatrecord',
            name='character',
        ),
        migrations.AddField(
            model_name='chatrecord',
            name='character_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='chatrecord',
            name='character_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='chatrecord',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chatrecord',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='chatrecord',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
