# Generated by Django 5.1.2 on 2025-09-24 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_remove_chatrecord_character_chatrecord_character_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatrecord',
            name='character_description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='chatrecord',
            name='character_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='chatrecord',
            name='top_k',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='chatrecord',
            name='top_p',
            field=models.FloatField(default=0.7),
        ),
    ]
