# Generated by Django 5.1.2 on 2025-09-24 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_chatrecord_character_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='greeting',
            field=models.TextField(default='你好，我可以为你做些什么？'),
        ),
        migrations.AddField(
            model_name='chatrecord',
            name='greeting',
            field=models.TextField(default='你好，我可以为你做些什么？'),
        ),
    ]
